package models

const (
	TASK_STATUS_UNASSIGNED = "Unassigned"
	TASK_STATUS_ONGOING    = "Ongoing"
	TASK_STATUS_COMPLETED  = "Completed"
	TASK_STATUS_ABANDONED  = "Abandoned"
)

var (
	TASK_STATUS = []string{TASK_STATUS_UNASSIGNED, TASK_STATUS_ONGOING,
		TASK_STATUS_COMPLETED, TASK_STATUS_ABANDONED}
)
